### PR TITLE
Add a container file to the repo to create a basic test image.

### PR DESCRIPTION
**Pull request by sefroberg**
First step to creating a container for test execution. This first piece should align with the InterOp Team's efforts.

### CODE REVIEW

**Comment by judovana** [comment]
What is this for?-)

**Comment by sefroberg** [comment]
> What is this for?-)

This is a the containerfile needed to add support for execution in the OpenShift CI by the Interop team.

**Comment by judovana** [comment]
Oh I see. I'm afraid I'm for no use with it:(

@jmtd  You have more insght into this?

**Comment by jmtd** [comment]
I'm afraid I don't know what the interOp team are doing. All I can say is this is a syntactically valid Containerfile, and it looks sensible.

**Pull request closed without merging**
