### PR TITLE
[OPENJDK-3339]Update Rhel 9 check to support more than just UBI images.

### PR DESCRIPTION
**Pull request by sefroberg**

### CODE REVIEW

**Review by judovana — APPROVED** [review]
It is quite uncommon to  use  string.concat(string). Feel free to keep it, But I would recommend to use more common string+string..

Also the if else is slightly weird. Does it compile?  I think it will complain that `return osCheck;`  is unreachable.  I would recommend  to simply  `return getImageUrl().contains(ubiVer.concat(target)) || getImageUrl().contains(elsVer.concat(target))` wdyt?

**Comment by sefroberg** [comment]
> It is quite uncommon to use string.concat(string). Feel free to keep it, But I would recommend to use more common string+string..
> 
> Also the if else is slightly weird. Does it compile? I think it will complain that `return osCheck;` is unreachable. I would recommend to simply `return getImageUrl().contains(ubiVer.concat(target)) || getImageUrl().contains(elsVer.concat(target))` wdyt?

The return statement is outside of if/else statements.  I ran this against a couple different versions of the images to make sure both paths of the if conditional are hit. That said, now that I look at it. I don't think I need the else { } block of code in there.

**Comment by judovana** [comment]
Oh my bad. To early morning. I read it as 
```
if (getImageUrl().contains(ubiVer.concat(target)) || getImageUrl().contains(elsVer.concat(target))) {
			return true;
		}
		else {
			return false;
		}
		return osCheck;
```

Still I would prefer `return getImageUrl().contains(ubiVer.concat(target)) || getImageUrl().contains(elsVer.concat(target)) ` but go as you need.

**Comment by sefroberg** [comment]
While I agree with your idea of streamlining the return code, I will also have to add the same type of check for the rhel 8 images soon. That was why I broke the code out into a separate method.

**Review by jmtd — APPROVED** [review]

**Review by vieiro — APPROVED** [review]
I agree with others in that the code is not very "idiomatic", but it does indeed do the job. Let's go for it. Thanks, @sefroberg !

**Pull request merged**
